# Generated by Django 2.2.7 on 2019-11-10 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordInRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='request',
            name='text',
        ),
        migrations.AddField(
            model_name='request',
            name='original',
            field=models.CharField(default=None, max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='request',
            name='purified',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='StopWord',
            fields=[
                ('word_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Word')),
            ],
            bases=('app.word',),
        ),
        migrations.CreateModel(
            name='WordPositionsInRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('wordInRequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.WordInRequest')),
            ],
        ),
        migrations.AddField(
            model_name='wordinrequest',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Request'),
        ),
        migrations.AddField(
            model_name='wordinrequest',
            name='totalIndex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TotalIndex'),
        ),
        migrations.AddField(
            model_name='totalindex',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Word'),
        ),
        migrations.CreateModel(
            name='RequestResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Request')),
            ],
        ),
    ]
