# Generated by Django 2.2.7 on 2019-11-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191110_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='original',
            field=models.CharField(default='', max_length=250),
        ),
    ]
