# Generated by Django 2.2.7 on 2019-11-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191110_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='original',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
