# Generated by Django 2.2.7 on 2019-11-10 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191110_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestresponse',
            name='proposal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposal_request_id', to='app.Request'),
        ),
        migrations.AlterField(
            model_name='requestresponse',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_request_id', to='app.Request'),
        ),
    ]
