# Generated by Django 2.2.7 on 2019-11-10 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191110_1605'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestResponse',
        ),
    ]
