# Generated by Django 2.2.7 on 2019-11-10 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_requestresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposal_request_id', to='app.Request')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request1_request_id', to='app.Request')),
            ],
        ),
    ]
