# Generated by Django 2.2.7 on 2019-11-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_requestresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='word',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
