# Generated by Django 2.2.7 on 2019-11-10 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20191110_1822'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StopWord',
        ),
    ]
