# Generated by Django 2.2.7 on 2019-11-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_stopword'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopWord',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
